const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
const SETUP_USER_ERROR = "SETUP_USER_ERROR";
const LOGOUT_USER = "LOGOUT_USER";
const VERIFY_USER_BEGIN = "VERIFY_USER_BEGIN";
const VERIFY_USER_SUCCESS = "VERIFY_USER_SUCCESS";
const VERIFY_USER_ERROR = "VERIFY_USER_ERROR";
const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER_BEGIN";
const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";

export {
  SETUP_USER_BEGIN,
  SETUP_USER_SUCCESS,
  SETUP_USER_ERROR,
  LOGOUT_USER,
  GET_CURRENT_USER_BEGIN,
  GET_CURRENT_USER_SUCCESS,
  GET_CURRENT_USER_ERROR,
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  VERIFY_USER_BEGIN,
  VERIFY_USER_SUCCESS,
  VERIFY_USER_ERROR,
};
