SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
SETUP_USER_ERROR = "SETUP_USER_ERROR";
LOGOUT_USER = "LOGOUT_USER";

export { SETUP_USER_BEGIN, SETUP_USER_SUCCESS, SETUP_USER_ERROR, LOGOUT_USER };
